### ISSUE TITLE
Track Discord username/ID

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/team#1]
We'll eventually want to setup some form of bots, like highfive's review pings, on Discord. It would be great to start populating that data now -- or at least support doing so.

I'm willing to take on the fieldwork of trying to track these down and making a pull request; I would rather not do the implementation work though to avoid stepping on any toes (I presume there's some churn currently).

**Comment by pietroalbini** [comment]
Yeah sure, I can review a PR about that. If we implement it though we'll need an easy way to get the ID of an user.

**Comment by khionu** [comment]
In the Discord client: User Settings -> Appearance -> Developer Mode. A Context Menu option called "Copy ID" is then added for most things, including users.

**Comment by Manishearth** [comment]
I think he means from the cli

**Comment by khionu** [comment]
I'd need elaboration, then.
