### ISSUE TITLE
I would like to join the moderation team (for a while)

### ISSUE THREAD

**Issue by fasterthanlime** [rust-lang/team#1006]
I've spent the last two days talking to a lot of people involved with the [RustConf Keynote Fiasco](https://blog.rust-lang.org/2023/05/29/RustConf.html), so I could make a public informed statement / summary about it.

However, in doing so, I've realized that in addition to the information I can responsibly make public, there's a whole side to this that shouldn't be made public at this time, but I would still like to help with.

As a result, I've decided to apply for a position on the moderation team.

## Why add anyone to the moderation team?

In short: burn-out, conflicts of interest re: the recent situation, and following this piece of advice from #671:

  * we suggest that the future Mod Team take special care to keep the team of a healthy size and diversity, to the extent possible. It is a thankless task, and we did not do our best to recruit new members.

## Why add me specifically?

I would rather it be someone else, and in fact, I encourage anyone who would be willing to serve on the moderation team for at least a little bit to step forward. I would also encourage people to encourage people who they know might do a decent job at it.

I've been active in the Rust space since 2019, mostly through my writings and videos as a content creator / educator. This has allowed me to meet with folks from various teams of the Rust project, Rust foundation, and RustConf. I maintain friendly relationships with a lot of them.

However, I have never been a member of any team, I am not beholden to any team's specific agenda. My ties with the 3 Rust orgs so far have been:

  * Received $5K from the foundation in 2023 for content creation
  * Was briefly asked by the project whether I wanted to join a team sometime in 2021/2022 (I didn't)
  * I was on the RustConf program committee in 2022

## What's my plan?

I would like my time on the moderation team (if it my application is accepted) to last only as long as it needs to. I would like to focus on several areas:

  * Helping to finish resolving the "RustConf Keynote Fiasco" internally as peacefully as possible (I unfortunately cannot give any more details publicly at this time)
  * **Leadership Council**: Facilitating in whatever ways I can the arrival of the [Leadership Council](https://github.com/rust-lang/rfcs/pull/3392), which heralds the death of the core team (and the leadership chat, implicitly)
  * **Recruitment**: Helping to grow and diversify the moderation team to better distribute the burden
  * **Professional training & support**: Working with the foundation to provide/require professional training for people serving on the moderation team so that they're better equipped to deal with complex moderation issues, as well as mental health support, and access to third-party mediators
  * **Specialization**: Seriously considering the idea of renaming and/or splitting the moderation team between "moderation" issues (GitHub, Discourse, external CoC violations) and "internal support/mediation" issues (interpersonal conflict, crisis of consensus/quorum, formal processes not being followed, etc.)
  * **Transparency**: Helping the Rust project as a whole achieve better transparency and regain public trust. This doesn't include all past issues, but it should be an important goal moving forward.
  * Thinking about the power held by subreddit moderators (disclosure: I was added to /r/rust's moderators on May 28), and whether there needs to be coordination between both teams. I only learned a few days ago that the "moderation team" and the "/r/rust mods" were two separate groups (that overlapped at various points)

I have not checked ahead of time with anyone regarding these: these are just on my mind.

## Will I have time to do this?

I'm setting aside time to do it. I'm not currently employed (I live off of sponsorship money through Patreon & GitHub Sponsors + severance from my last job), but I do normally try to make technical contributions (see my work on rust-analyzer proc-macro compatibility for example) to Rust, or educational contributions to Rust.

I most likely won't have time to do these initially, or as much, or perhaps at all for a while. That's okay with me.

## Why is this a github issue? Surely this is not how you apply to the mod team?

Well!

I've been asking around and nobody can tell me what the procedure is for applying to the moderation team.

[This page says](https://forge.rust-lang.org/governance/index.html#moderation-team):

> Its members are chosen directly by the core team, and should be community members who have demonstrated the highest standard of discourse and maturity. 

Except the core team is about to be dismantled by virtue of the leadership council being established. In the interim, it seems it would fall to the "(interim) leadership chat" to step in? The problem is, I have the feeling that document is fairly outdated.

The [Moderation team page](https://www.rust-lang.org/governance/teams/moderation) says nothing about applying. There is an "E-mail" button, and I was given discord handles, but it felt wise for there to be a public trace for my application, so that a larger number of people can be aware of it (and potentially be inspired to apply in turn).

I have no idea who will be ultimately responsible for 👍 -ing or 👎 -ing this, but, well, here we are. I am willing to discuss my application more in private or in public, with anyone who reaches out.

(cc @khionu and @technetos)

**Comment by Manishearth** [comment]
More background: back when I was on mods I was hoping to add a better onramp, the trickiest thing being that moderation needs its members to have a baseline of trust from the community and it's hard to evaluate that. I did in part design the venue mod policy to help bootstrap mods, and when the old mod team resigned the new mods were chosen from that group, but it has not been exercised as much as I'd hoped. But beyond "become a venue moderator" (which itself is not specified) there is no formal onramp.

I've previously written up [my ontology of the types of trust in moderation](rust-lang.zulipchat.com/#narrow/stream/369838-rfc-leadership-council-feedback/topic/moderation.20onboarding/near/342209001) and I think it may be useful for people attempting to design onramps today, or people who plan to evaluate applications like this.

I also do not think an onramp must be designed to evaluate this application.

**Comment by Manishearth** [comment]
Oh, also, one thought I had been noodling around in the past about processes for adding new moderators is that in cases where the moderation team is _not_ that familiar with a candidate, we pre-announce that candidate's nomination, and run a process somewhat similar to that being used for selecting council reps where people are allowed to object  privately, and have the option to have their objection shared with the nominee or not (useful in cases where someone has an objection that they feel can be resolved through discussion). The existing moderators review the objections and evaluate if they are sufficient to block selection.

**Comment by skade** [comment]
I am highly critical of extending the scope of the moderation team to mediation. These are 2 different functions and conflict resolution is a function of leadership in general. It's an obligation of each and every leader, mediation/supervision is a resource they can get into.

I also want to note that the application does _not_ include moderation specific things (experience level, approach to moderation, etc.)

As [graydons post](https://graydon2.dreamwidth.org/307105.html) mentions, this is stuff for professionals.

I also want to log here that all of these proposals were given by me to the moderation team and the foundation board in 2021 and neglected/denied, I hope it will be different this time.

**Comment by fasterthanlime** [comment]
> conflict resolution is a function of leadership in general.

Although I agree with that, I think we both know reality has been a bit more complicated in the past. It's hard to give more details without accidentally making some more things public, so I'll accept that my point is weaker without specifics.

I also think folks in leadership positions show different technical and social abilities, and I wouldn't want to detract from the diversity we have there.

It seems to me that saying "mediation/supervision is a resource they _can_ get into" is less than what we _ought_ to do - I specifically bring up professional training and access to professional mediators in my application.

But also, don't mistake a quick braindump of "things that are on my mind" with a "moderation team RFC". I'm at the "getting to know people already on the moderation team" stage of all this.

---

> I also want to log here that all of these proposals were given by me to the moderation team and the foundation board in 2021 and neglected/denied, I hope it will be different this time.

I'm interested in the contents of these, do you have a link to them? I'm happy to discuss this privately if needed, as it seems really important for prior art to be considered here.

**Comment by fasterthanlime** [comment]
> As [graydons post](https://graydon2.dreamwidth.org/307105.html) mentions, this is stuff for professionals.

Ah, I forgot to mention: if the outcome of my application is that a proper (publicly known / publicized) "mediation / people resource" team ends up being hired by the foundation and stays close to day-to-day operations of the project, then I'll be very, very happy.

As mentioned earlier, I don't specifically want to do this myself. I don't think I can "wing it" and have specifically requested the foundation pays for additional training if my candidacy is seriously considered. But I also acknowledge that trust and "perceptions of neutrality/fairness/legitimacy" play an important part in mediation and that these have been a challenge in the past.

(Again I'm having to keep this relatively vague due to the public nature of this discussion).

**Comment by fasterthanlime** [comment]
I'm in touch with folks internally, and I believe this issue has served its purpose - closing for tidying reasons.
