### ISSUE TITLE
RFE: Indicate the representation of Leadership Council members

### ISSUE THREAD

**Issue by cuviper** [rust-lang/team#1014]
For this page: https://www.rust-lang.org/governance/teams/leadership-council

The folks on the council are each there to represent a particular top-level team, but there's no indication of that in the member list. Even having broad context, some of them are active in multiple areas of the project, so their particular connection for the council is not obvious. But I think we should make it clear even to visitors that have no such context.

**Comment by ehuss** [comment]
Just for clarification to avoid confusion: the word *affiliation* in the context of the RFC was being used for association with employment (which I think we should also track somewhere). For teams, I think *representation* might be the appropriate way to phrase it.

**Comment by cuviper** [comment]
Thanks for pointing that out -- I changed the title.

**Comment by cuviper** [comment]
Fixed by #1182, thanks @dtolnay!
