### ISSUE TITLE
Discord names are different from the actual ones

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/team#102]
For example:

https://github.com/rust-lang/team/blob/7b598f694c6f1828210179cd37a4fbf29e8ec9fa/teams/wg-net-async.toml#L12-L13

https://github.com/rust-lang/team/blob/7b598f694c6f1828210179cd37a4fbf29e8ec9fa/teams/wg-net-web.toml#L12-L13

We should sync them with actual WGs?

**Comment by khionu** [comment]
Honestly, the invite section should use the Vanity URL `discord.gg/rust-lang`. When you're invited to the Discord, you can't access any channel until you agree to follow the CoC, which won't be apparent if people don't follow the main invite.

**Comment by JohnTitor** [comment]
These teams are archived, closing.
