### ISSUE TITLE
Enable branch protection for rust-lang/rfcs repo

### ISSUE THREAD

**Issue by weihanglo** [rust-lang/team#1096]
Every time when I finish a review an RFC, I nearly click the merge button.

RFCs are the essential part of public discussions of Rust features. We probably want to prevent it from accidental merges to reduce confusions.

<img width="300" alt="image" src="https://github.com/rust-lang/team/assets/14314532/16529ca9-1f92-496c-93c5-d96bd2fea5d2">

**Comment by ehuss** [comment]
What restrictions would you suggest for the rfc repo? Some people need to be able to merge PRs, so we would need to define that policy.

**Comment by rami3l** [comment]
@ehuss Is it reasonable to require at least one approving review? I think the overall bandwidth of the Rust team should allow this.

**Comment by WaffleLapkin** [comment]
Could we maybe make it bors managed? Most bors features are useless I guess, but `@bors r+`'ing PR accidentally is much harder than pressing the button 😅 

Alternatively we might want to require fcp completion, but I'm not sure we can somehow gate the button on labels...
