### ISSUE TITLE
Update Rust Team Information

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/team#146]
## Introduction
Hello everyone, The governance working group has been looking to formalise some of the current structure of Rust Programming Language organisation that we have found to be currently unclear and under or undocumented. One example of this is that some of the team's current membership is out of date with [`rust-lang/team`]. So we're asking that team leads (or relevant members) update their roster and to synchronise their team permissions with GitHub. This will reduce some of current overhead in managing our infrastructure.

## How To Update Team Information.
1. Clone the [`rust-lang/team`] repository.
2. Visit your team's information available in the [`teams/` directory][team-dir].
	* Refer to the [TOML schema][team-schema] for how to configure the file.
3. Check that all of the names in `members` matches what you expect. Add any recent/missing team members, and remove any inactive members.
    * When adding members, also ensure that they are also present in the [`people/` directory][people-dir].
	* The command `cargo run add-person <github-username>` inside the team repo will load publicly available information.
	* If the member is not available, please contact them directly, asking them to add their information to [`rust-lang/team`].
4. Make sure your team contains something like the following code snippet. Importantly that you have the `rust-lang` org in your org. This will synchronise your team information here with the team information on GitHub. Your team may already have this and if so no action is required. 
```toml
[github]
orgs = ["rust-lang", "rust-lang-nursery"]
```
6. Run `cargo run check` inside the team repo to ensure the changes you made are valid.

[team-dir]: https://github.com/rust-lang/team/tree/master/teams
[team-schema]: https://github.com/rust-lang/team/blob/master/docs/toml-schema.md#teams
[people-dir]: https://github.com/rust-lang/team/tree/master/people
[`rust-lang`]: https://github.com/rust-lang/
[`rust-lang/team`]: https://github.com/rust-lang/team
[`rust-lang-nursery`]: https://github.com/rust-lang-nursery
[`rust-central-section`]: https://github.com/rust-lang/rust-central-station

## Potential Questions
> How do I decide whether a person should be added or removed from my team?

The Goverance Working Group's purpose is to provide guidance, not decisions. It is up to each team's discretion to decide their roster and what qualifies for membership.

> How important is it to update this?

Having you and your team's information up to date and synchronised with GitHub will help reduce some overhead in adminstrating Rust's infrastructure, and will help in the future lay groundwork for proposals for formalising Rust's access policy.

> How can I see the difference between GitHub's team membership and `rust-lang/team`?

With your new changes to the team repository you can check the difference between the team repo and the GitHub teams. To do that, clone the [`rust-central-section`] repository, set the `GITHUB_TOKEN` environment variable to a valid GitHub personal access token (you need to be a member of the [`rust-lang`] and [`rust-lang-nursery`] orgs) and run this command:
```
cargo run --bin sync-github -- --team-repo <path-to-your-team-repo>
```

The tool will output the differences between GitHub and the team repo, if present.

> Hey, I know what changes I want to make, but I don't have the time to make a PR, is there any way to send a list?

Yes! You can email your desired changes to <goverance@rust-lang.org>, and I or another member of the working group will make a PR with those changes. 

## Tracking For Confirmation Of Updated Information

- [x] Cargo: @ehuss, @nrc
- [x] Clippy: @Manishearth, @oli-obk
- [x] Community: @rust-lang/community
    - [x] Content: @skade, @adityac8, @nasa42, @wezm
    - [x] Events: @skade
    - [x] RustBridge: @fmoko
    - [x] Survey: @Manishearth
- [x] Compiler: @nikomatsakis
- [ ] Core: @rust-lang/core
- [ ] Crates.io: @sgrif, @ashleygwilliams
- [x] Dev Tools: @killercup, @Manishearth
- [ ] IDEs: @nrc, @Xanewok
- [x] Infra: @aidanhs, @pietroalbini
- [x] Lang: @nikomatsakis, @joshtriplett
- [x] Libs: @alexcrichton
- [x] Reference: @Havvy
- [x] Release: @Mark-Simulacrum 
- [x] Rustdoc: @QuietMisdreavus

**Comment by fmoko** [comment]
@XAMPPRocky We have two additional orgs that most of us are in, `rust-community` and `rustbridge`, but those currently fail the checker. Is there any way we can include them?

**Comment by pietroalbini** [comment]
@fmoko to manage additional organizations y'all need to invite @rust-lang-owner as **owner** of those orgs, as it needs to invite people and manage teams. Once that's done and someone from infra accepts the invite you can tweak the list of allowed orgs in `config.toml`.

**Comment by Manishearth** [comment]
One thing this issue doesn't make clear: all of this stuff is added to a GitHub org team, and you should also make sure that the org team has write, maintainer, or admin access to the repo.

**Comment by fmoko** [comment]
FWIW all of community team was updated

**Comment by XAMPPRocky** [comment]
@fmoko Thanks! Would you also be able to confirm if the RustBridge team is up to date?

**Comment by fmoko** [comment]
@XAMPPRocky yep

**Comment by rylev** [comment]
This issue is old enough now that it's not particularly useful. We are slowly moving more automation over to the team repo which helps keep the teams up-to-date. However, it is still the case that teams do drift over time. If we decide to do another one of these big cleanups, I think it's best to do that in another issue.
