### ISSUE TITLE
Team Archival

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/team#190]
Not all teams or working groups are permanent efforts, we should have the ability to reflect that in the team repo.

## Potential Solutions

* `archived` folder in `teams/` containing the team files.

**Comment by pietroalbini** [comment]
I don't think it's worth to keep those files laying around, we can just delete them.

**Comment by XAMPPRocky** [comment]
I'm strongly against that course of action. I believe that it's important to recognise people for their work. Deleting them makes these efforts hard to find, while it is *possible* that someone can look through the git history, practically speaking people aren't going to do that without already knowing what to look for. In the future I would also like to document these past efforts on the website. This important not only for historical or archival reasons, but for the current day as well, because it's likely that people are putting their work for Rust on their CV, and providing a easy way to verify that information is important.

**Comment by khionu** [comment]
I'd suggest naming the folder "Emeritus", as in "Emeritus Alumni"

**Comment by XAMPPRocky** [comment]
@khionu Reading the definition of that word, that seems to be used to refer to an individual and not a group?

> emeritus | ɪˈmɛrɪtəs, iːˈmɛrɪtəs |
adjective
(of the former holder of an office, especially a university professor) having retired but allowed to retain their title as an honour: emeritus professor of microbiology | [postpositive] : the National Gallery's director emeritus.

**Comment by khionu** [comment]
It's an adjective, it can be used in plural. In the usage I gave as an example, it actually is plural, as it refers to the collective Alumni that hold Emeritus status.

**Comment by pietroalbini** [comment]
Well, from any practical point of view moving a team to a subfolder is the same as deleting it, as it will make that team invisible to the repo automation: its content will not be validated, permissions will not be granted and it won't show up on the website.

> I believe this is important not only for historical or archival reasons, but for the present day as well, because it's likely that people are putting their work for Rust on their CV (I know I am), and providing a easy way to verify that information is important.

We already have the "alumni" team, and all team members who don't contribute anymore are supposed to be added to it.

**Comment by khionu** [comment]
Then there's existing process for this? Should everything be set here for that?

**Comment by XAMPPRocky** [comment]
@pietroalbini Yeah, but alumni is quite vague. I know that currently it's equivalent to deleting them in terms of automation, but in the future I would want to change that.

@khionu There's no process, alumni existed on the old website and it was just carried over into teams. Most people aren't aware of it so they just delete themselves, (even core members forget alumni exists).

**Comment by khionu** [comment]
Then we should definitely fix that

**Comment by rylev** [comment]
We have had the archive folder for quite some time. I think this can be closed now.
