### ISSUE TITLE
Sync with GitHub teams

### ISSUE THREAD

**Issue by nrc** [rust-lang/team#2]
Being able to ensure the teams on rust-lang are in sync with this data would be awesome.

**Comment by XAMPPRocky** [comment]
@pietroalbini This issue looks like it can be closed.

**Comment by Manishearth** [comment]
I think it's only partially done?

**Comment by pietroalbini** [comment]
Yep, the technical side is done, but not every team was migrated.

**Comment by XAMPPRocky** [comment]
I was thinking about finishing this issue, in total there's about ~42 teams in the repository that don't have github sync. I was wondering though if I should make a PR for each team and `r?` the respective leads, or should I group the changes into smaller batches?

**Comment by pietroalbini** [comment]
There are two things that are going to simplify the process:

* Not all the teams actually need to be synchronized with GitHub: if you prepare a list of all the teams that are not synchronized yet me or someone else from core can prune it up.
* I don't think approval from the team leads is needed if *no changes are made* to the teams on GitHub. What I'd do is prepare a single PR batching all the noop changes, and then a PR `r?`d to each team lead for the teams that actually have changes.

To check which teams have deltas between GitHub and the team repo I'd make all the changes in your local clone on a single branch, clone [sync-team](https://github.com/rust-lang/sync-team) and run (with your personal `GITHUB_TOKEN` environment variable):

```
cargo run -- github --team-repo ~/path/to/your/team/repo/clone
```

The command will do a dry run of the synchronization without actually making any changes to GitHub (the `--live` flag is needed for that), and print the diff. Note that last time I checked there are some changes `sync-team` will try to run over and over again, and you can ignore them.

**Comment by XAMPPRocky** [comment]
I've included the list below it was made by running `grep -rL 'orgs ='` and then removing the teams in archive, alumni, infra-admins from it.

```
teams/reference.toml
teams/wg-rustfix.toml
teams/windows.toml
teams/leads.toml
teams/arm.toml
teams/web-presence.toml
teams/wg-meta.toml
teams/wg-grammar.toml
teams/icebreakers-cleanup-crew.toml
teams/wg-debugging.toml
teams/wg-gamedev.toml
teams/wg-unsafe-code-guidelines.toml
teams/operations.toml
teams/icebreakers-llvm.toml
teams/wg-wasm.toml
teams/wg-compiler-performance.toml
teams/ides.toml
teams/wg-parallel-rustc.toml
teams/wg-bindgen.toml
teams/wg-secure-code.toml
teams/docs.toml
teams/twir.toml
teams/wg-cli.toml
teams/wg-rustup.toml
teams/mods.toml
teams/mods-discord.toml
teams/wg-leads.toml
teams/wg-pgo.toml
teams/wg-self-profile.toml
teams/wg-rls-2.toml
teams/mods-discourse.toml
teams/wg-embedded.toml
teams/wg-nll.toml
teams/wg-llvm.toml
```

**Comment by pietroalbini** [comment]
@XAMPPRocky turned it into a checklist, and added comments on why some of them are not checked.

**Comment by XAMPPRocky** [comment]
@pietroalbini Thanks! So does the mean this can now be closed?

**Comment by pietroalbini** [comment]
@XAMPPRocky no, the checked teams are the ones that should be synchronized.

**Comment by XAMPPRocky** [comment]
Ah okay. I think for some of the teams we should still sync them with the main org even if it might not be useful now, if only to give those members "rust-lang" under their profile on GitHub, it's small but having the badge is a bit of recognition for their work.

**Comment by pietroalbini** [comment]
@XAMPPRocky makes sense, checked two extra teams (twir and mods-discourse).

**Comment by rylev** [comment]
All GitHub teams are now controlled by this repo.
