### ISSUE TITLE
How to add observers?

### ISSUE THREAD

**Issue by skade** [rust-lang/team#35]
I have the status of observer to core, which is a stepping stone to membership, but not full membership.

I'd like the info to be presented in the interest of transparency, but also don't want to claim full.

**Comment by pietroalbini** [comment]
Maybe we can add a `core-observers` subteam with just you in it?

**Comment by skade** [comment]
I think that's actually a pragmatic and quick solution. @nikomatsakis ?

**Comment by Manishearth** [comment]
Done in #33
