### ISSUE TITLE
alumni are added to the all mailing list

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/team#361]
As @pietroalbini [discovered](https://github.com/rust-lang/team/pull/356#issuecomment-643200002) in #356, apparently working group alumni are added to the all mailing list. In general, I don't think alumni should be on the mailing list, but it seems especially inconsistent to have folks being added to the mailing list **only** when they become alumni and not before!

**Comment by nikomatsakis** [comment]
cc @XAMPPRocky

**Comment by XAMPPRocky** [comment]
Hmm, just looking at the team repo and [`sync-mailgun`] and I can’t really tell why this would be the case.

[`sync-mailgun`]: https://github.com/rust-lang/rust-central-station/tree/master/sync-mailgun

**Comment by pietroalbini** [comment]
That's because `alumni` is considered a team, and `all@` is generated from all the teams.

**Comment by jackh726** [comment]
This might have been fixed in #380
