### ISSUE TITLE
Add zulip stream key to website data

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/team#383]
Similar to how we have `discord` currently that allows showing a team's channel on the website it would be nice if we could do the same for Zulip.

Related: https://github.com/rust-lang/www.rust-lang.org/issues/1190

**Comment by pietroalbini** [comment]
Implementation note if someone wants to do this: the key should be something like:

```
zulip-stream = "t-infra"
```

From it we can reconstruct the URL on the website:

```
https://rust-lang.zulipchat.com/#narrow/stream/{zulip-stream}
```
