### ISSUE TITLE
Finer-grained GitHub permissions synced with teams

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/team#393]
In GitHub, I just created a crates.io triage team that only has access to the crates.io repo and only has triage permissions to it. When this repo supports syncing everything with GitHub teams, it'd be nice to have a way of specifying more finer-grained permissions for a team.

**Comment by Mark-Simulacrum** [comment]
I believe this is currently supported, e.g., https://github.com/rust-lang/team/blob/master/repos/rust-lang/cc-rs.toml#L7
