### ISSUE TITLE
Set up for the t-lang/doc team

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/team#443]
I talked with Josh and other folks, and propose to extend the current reference team to the "lang docs" team in order to maintain more docs like nomicon.

For context: https://rust-lang.zulipchat.com/#narrow/stream/196563-t-lang.2Fwg-meta and https://github.com/rust-lang/lang-team/issues/47
cc @rust-lang/lang for the approval

**Comment by joshtriplett** [comment]
:+1:
