### ISSUE TITLE
Use GitHub IDs instead of usernames for permissions

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/team#51]
This will prevent issues when an org member changes their username.

**Comment by Manishearth** [comment]
Since usernames is more convenient, how about requiring both and having a CI job that fails on mismatch?

**Comment by Manishearth** [comment]
(As in, it's easy to mess up an ID, not a username, but usernames can change, so having both is good.)

**Comment by pietroalbini** [comment]
Yep, we still want to store the username on the repo since it's needed for things like the website. My main worry about implementing this is that adding users is going to be more of a pain. We probably want a command like:

```
cargo run add-person pietroalbini
```

...that automatically fetches the full name, the ID and when possible the email address.

**Comment by pietroalbini** [comment]
Some notes for the future myself when I finally get time to work on this:

The blocker for adding IDs to this repo is that we need a way to validate them. Unfortunately it's practically impossible to validate IDs without a GitHub token, since the GraphQL API is restricted only to authenticated users and the number of REST calls would exceed the unauthenticated rate limits.

For local usage this is not an huge issue, as we can provide a command (`cargo run add-person`) that fetches the right ID for you without a token and we can show a warning when running the validation.

Potentially skipping the validation locally means we absolutely need to do the full one on CI though, including in PR builds. Adding our own token there basically means leaking it to the world, and we can't do that. If we switch to Azure Pipelines we can instead use their one, which *should* be available even in PRs.

To extract the token from Azure Pipelines we need to persist credentials after checkout:

```yaml
- checkout: self
  persistCredentials: true
```

And then we can fetch the content of the Authorization header with:

```bash
git config -l | grep "extraheader=AUTHORIZATION" | awk '{print($2 " " $3)}'
```
