### ISSUE TITLE
Consider disabling clippy in CI

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/team#560]
Currrently our CI is broken due to a bump in the stable compiler, resulting from a new Clippy lint being added. While the same can happen from just rustc, rustc adds new lints very rarely when they affect normal, 'good' code; the same is not true of clippy.

Given that we likely want the CI in this repository to always pass (so that we can e.g. land PRs without worrying about fixing CI), it's not clear to me that having clippy is worthwhile. Alternatively, we could consider pinning the stable compiler used for the clippy build, but that has other disadvantages.

**Comment by Manishearth** [comment]
We should do this, yeah
