### ISSUE TITLE
Update on the recent issue?

### ISSUE THREAD

**Issue by rubyFeedback** [rust-lang/team#673]
khionu closed the discussion, so that's fine, but people are wondering. Have there been
any news pertaining to the issues?

**Comment by rubyFeedback** [comment]
(I'll auto-close it just so that it does not get too active since it's a low priority question.)

**Comment by khionu** [comment]
[Here is the initial response](https://blog.rust-lang.org/inside-rust/2021/11/25/in-response-to-the-moderation-team-resignation.html)
> Updates on next steps will be shared with the project and wider community over the next few weeks.

This is the weekend after Thanksgiving in the US, so that affects all Rust activity in general.
