### ISSUE TITLE
Changing project visibility is only possible for rust-lang admins

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/team#841]
In https://github.com/orgs/rust-lang/projects/21/settings I tried to change the visibility settings but it tells me

> Only organization owners can change project visibility.

I gave access to the `all` group, but ideally it would have read access for everyone

**Comment by Mark-Simulacrum** [comment]
I adjusted the setting to allow admins for projects to change their visibility; I think that makes sense. A little surprised the default is different.
